# Generated by Django 5.2.3 on 2025-07-17 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=100)),
                ('level_of_study', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisDefenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_title', models.CharField(max_length=100)),
                ('thesis_abstract', models.TextField()),
                ('field', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uni_thesis.student')),
            ],
        ),
        migrations.CreateModel(
            name='DefenceSession',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uni_thesis.thesisdefencerequest')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_sessions', to='uni_thesis.professor')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_sessions', to='uni_thesis.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('evaluator', 'Evaluator'), ('observer', 'Observer')], max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_thesis.professor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_thesis.thesisdefencerequest')),
            ],
            options={
                'unique_together': {('professor', 'request', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('selected', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_thesis.professor')),
            ],
            options={
                'unique_together': {('professor', 'date', 'start_time')},
            },
        ),
    ]
