# Generated by Django 5.2.3 on 2025-07-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0002_student_professor_thesisdefencerequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Specialization',
            new_name='specialization',
        ),
    ]
