# Generated by Django 5.2.3 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0003_rename_specialization_professor_specialization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professorassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='professorassignment',
            constraint=models.UniqueConstraint(fields=('professor', 'request'), name='unique_prof_request'),
        ),
    ]
