# Generated by Django 5.2.3 on 2025-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0008_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Admin', 'Admin')], default=2, max_length=20, verbose_name='role'),
            preserve_default=False,
        ),
    ]
