# Generated by Django 5.2.3 on 2025-08-24 10:01
import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0009_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='defencesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defencesession',
            name='end_time',
            field=models.TimeField(default=datetime.time(1, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defencesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='uni_thesis.professor'),
        ),
        migrations.AddIndex(
            model_name='defencesession',
            index=models.Index(fields=['date', 'start_time'], name='uni_thesis__date_d8b2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['professor', 'date', 'start_time'], name='uni_thesis__profess_59899b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['professor', 'available', 'date', 'start_time'], name='uni_thesis__profess_a180eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='defencesession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='defencesession',
            constraint=models.CheckConstraint(condition=models.Q(('evaluator', models.F('observer')), _negated=True), name='evaluator_and_observer_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('professor', 'date', 'start_time', 'end_time'), name='uniq_prof_date_start_end'),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='selected',
        ),
    ]
