# Generated by Django 5.2.3 on 2025-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0010_alter_timeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='uniq_prof_date_start_end',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('professor', 'date', 'start_time'), name='uniq_prof_date_start_end'),
        ),
    ]
