# Generated by Django 5.2.3 on 2025-08-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_thesis', '0011_remove_timeslot_uniq_prof_date_start_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='field_of_study',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('law', 'Law'), ('business', 'Business'), ('arts_humanities', 'Arts & Humanities')], max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('engineering', 'Engineering'), ('medicine', 'Medicine'), ('law', 'Law'), ('business', 'Business'), ('arts_humanities', 'Arts & Humanities')], max_length=32),
        ),
    ]
