from .user import UserCreateSerializer, UserUpdateSerializer
from .student import StudentCreateSerializer, StudentUpdateSerializer
from .professor import ProfessorCreateSerializer, ProfessorUpdateSerializer